version: '3.3'
services:
  db:
    image: mariadb # Base de datos a utilizar para los cms
    container_name: mydb # Nombre del container
    restart: always
    volumes: # Volumen de persistencia de datos
      - ./data-mariadb:/var/lib/mariadb
      - ./mariadb:/root/mariadb
    environment: # Variables de entorno
      - MARIADB_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=YOUR_ADMIN_PASSWORD
      - MARIADB_DATABASE=wordpress
      - VIRTUAL_HOST: your-domain.com
    ports: # Puertos
      - 80:3306

